### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by acburdine** [usmanhalalit/pixie#105]
Hey all,

First, I want to say thanks for the great query builder that Pixie is. I've been using it for a while now, and it has been very useful.

To make it even better, I've had some ideas about stuff that could be done in this library to make it even better. Before I start in on actually implementing any of these, however, I thought it would be a good idea to put them here and see what the general response is on them.

- [x] .editorconfig file

[EditorConfig](http://editorconfig.org) is a great tool for standardizing file spacing, tabs, etc. While it doesn't do anything functionality-wise, it would help to make the code more readable.

- [x] PHP CodeSniffer

Along with the .editorconfig file, [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer/) will also help to beautify the code/make it more readable. This one might take some discussion, as people use different styles of coding. The one I would personally recommend is [PSR-2](http://www.php-fig.org/psr/psr-2/) as the current codebase seems to follow it for the most part, and it's the one recommended by the php-fig.

- [ ] Better Testing
- [ ] Code Coverage

This would probably take a decent amount of work (to which I'm willing to contribute), and isn't _super_ necessary, but it would be nice to have testing using a stubbed database (see [here](https://phpunit.de/manual/4.8/en/database.html) for details) to further test the correct implementation/idiosyncrasies of database interaction. Also, it would be nice to use something like [php code coverage](https://github.com/sebastianbergmann/php-code-coverage) to generate unit testing coverage reports).

These are just a couple of ideas that I had, so let me know what you think!

/cc @usmanhalalit @neoascetic

**Comment by usmanhalalit** [comment]
Thanks @acburdine for all your contribution.

I agree with the PSR-2 thing, though mostly we are there. PHP Code Sniffer can help. If we follow this then EditorConfig seems unnecessary to me.

Agree with the testing point, but yes it's a whole lot of work and at this moment it is not super important. Currently I am looking forward to releasing 1.1 version. For this I need to get familiar with all the PRs and clean up all the things.

**Comment by acburdine** [comment]
@usmanhalalit I'll get to work implementing php code sniffer but I still think editorconfig would be nice -> mainly because having something there that forces you to use the right settings with spaces/tabs can be helpful when actually doing the code. Php code sniffer will flag tab/space inconsistency in the Travis suite, but in my opinion it would be nice to catch it before that. And it's just one file :)

**Comment by usmanhalalit** [comment]
Okay, we can go with editorconfig.

**Comment by acburdine** [comment]
Cool. If there's anything more to be done before releasing a 1.1 version, let me know :smile:
