### ISSUE TITLE
orderBy method DESC/ ASC

### ISSUE THREAD

**Issue by javasworks** [usmanhalalit/pixie#107]
Hi,
I couldn't find it in the documentation. Is there a method to do this? Or should we use the _Raw Query_ ?

Thanks,
Bagus

**Comment by Fishy49** [comment]
You can pass the direction (`ASC` or `DESC`) as the second argument:

`$query->orderBy('field', 'DESC');`

Default is `ASC`

**Comment by javasworks** [comment]
ha! :D thanks Fishy49
