### ISSUE TITLE
Schema handeling

### ISSUE THREAD

**Issue by matthieusieben** [usmanhalalit/pixie#11]
Would it be possible to add the ability to create (and, eventually, update) database schema?

**Comment by TCB13** [comment]
This would be a great addition, however I need to agree with @neoascetic at some point this will make pixie way to much complex than it needs to be. @matthieusieben if you're looking for schema management you might want to take a look at Laravel framework.

**Comment by marcossffilho** [comment]
I think that schema functions should be managed by the migration library, and not by the query builder.

**Comment by TCB13** [comment]
#138 would close this.
