### ISSUE TITLE
whereNotNull undefined

### ISSUE THREAD

**Issue by ppalladino** [usmanhalalit/pixie#110]
I am running v1.0.2 and for the most part everything works as documented (great lib btw!), however, I get an exception when accessing the whereNotNull method. 

```
Fatal error: Call to undefined method Pixie\QueryBuilder\QueryBuilderHandler::whereNotNull()
```

Below is my implementation. Any help would be appreciated. Thanks!

```
$query = QueryBuilder::table('companies');
$query->whereNotNull('deleted');
return $query->get();
```

**Comment by acburdine** [comment]
@ppalladino 1.0.2 is over 2 years out of date. There should be a new release sometime soon; however, the documentation is only correct for master :confused: 

If you want to use the master branch via Composer, just use `dev-master` as the version string.

**Comment by ppalladino** [comment]
Ah! OK, thanks. I'll give that a shot this weekend.
