### ISSUE TITLE
How to set parameters(wait_timeout, interactive_timeout, net_read_timeout)?

### ISSUE THREAD

**Issue by maranqz** [usmanhalalit/pixie#113]
How to set parameters(wait_timeout, interactive_timeout, net_read_timeout) through the $config to "new \Pixie\Connection('mysql', $config);".

Does not work
![image](https://cloud.githubusercontent.com/assets/3991984/12854090/c374e9e6-cc48-11e5-889d-ad7e8acabd13.png)

Thank you in advance.

**Comment by usmanhalalit** [comment]
@neoascetic do you have any idea?

**Comment by neoascetic** [comment]
It should work and it worked for me... let me check

**Comment by neoascetic** [comment]
I have no idea why it doesn't work for @maranqz, because it works well for me. Maybe there are no timeouts in fact?

**Comment by usmanhalalit** [comment]
Thanks for checking @neoascetic
