### ISSUE TITLE
Uncaught exception 'ReflectionException'

### ISSUE THREAD

**Issue by cmjunior** [usmanhalalit/pixie#115]
I´m testing pixie, and had a problem to run in a linux fresh environment with:
apache 2.2 and PHP 5.3.3:

I created a class DBhandler as following:

class DBHandler {
    protected $_QueryBuilder;

    function __construct() {
        require ".././vendor/autoload.php";
        include_once '../config/db.php';

        $config = array(
            'driver' => 'mysql',
            'host' => DB_HOST,
            'database' => DB_NAME,
            'username' => DB_USERNAME,
            'password' => DB_PASSWORD,
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
        );

        $connection = new \Pixie\Connection('mysql', $config);
        $this->_QueryBuilder = new \Pixie\QueryBuilder\QueryBuilderHandler($connection);
    }

```
[Wed Feb 17 11:12:35 2016] [error] [client 192.168.92.1] PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Pixie\\EventHandler does not have a constructor, so you cannot pass any constructor arguments' in /var/www/html/djfv/webservice/verba/vendor/usmanhalalit/viocon/src/Viocon/Container.php:138
Stack trace:
#0 /var/www/html/djfv/webservice/verba/vendor/usmanhalalit/viocon/src/Viocon/Container.php(138): ReflectionClass->newInstanceArgs(Array)
#1 /var/www/html/djfv/webservice/verba/vendor/usmanhalalit/viocon/src/Viocon/Container.php(110): Viocon\\Container->instanciate('\\Pixie\\EventHan...', Array)
#2 /var/www/html/djfv/webservice/verba/vendor/usmanhalalit/pixie/src/Pixie/Connection.php(54): Viocon\\Container->build('\\Pixie\\EventHan...')
#3 /var/www/html/djfv/webservice/verba/db/DBHandler.php(25): Pixie\\Connection->__construct('mysql', Array)
#4 /var/www/html/djfv/webservice/verba/model/Verba.class.php(13): DBHandler->__construct()
#5 /var/www/html/djfv/webservice/verba/v1/index.php(18): Verba->__construct()
#6 {main}\n  thrown in /var/www/html/djfv/webservice/verba/vendor/usmanhalalit/viocon/src/Viocon/Container.php on line 138
```

Aparently the error is in using the constructor with arguments, but It´s in the documentation, right?

Please any help is welcome.

**Comment by usmanhalalit** [comment]
That's weird!
I'm totally unable to reproduce the issue.
Can you please use dev-master and check?

**Comment by Kaimite** [comment]
Juste for info : 
On my dev machine / preprod machine / own dedicated server (OVH) works fine.
On my production machine (PHP Version 5.3.3-7+squeeze19) same error... 

Maybe en php bug... don't know.

Kaimite
