### ISSUE TITLE
Use an existing connection

### ISSUE THREAD

**Issue by sirhubber** [usmanhalalit/pixie#117]
Hello!

First of all, I think this library is great, there are a lot of nice tools and frankly, I find it more beautiful than all of the other QueryBuilder's I've seen.

More onto the question, is there anyway to use an existing PDO connection with this library? Because if I created this big application with a lot of twists and turns, it would be nice to be able to reuse the connection, seeing it as two connections for the same database is not extremely necessary.

I saw that the "setPdoInstance"-method is public, hence that could be used, but it seems impossible to create a Connection instance without specifying connection configuration settings into the constructor.

Love to hear your thoughts ~

**Comment by sirhubber** [comment]
Hello again, I found out you could do something like this:

`class ExtendedConnection extends Pixie\Connection {
	public function __construct(\PDO $connection)
	{
		$this->adapter = 'mysql';
                $this->setPdoInstance($connection);
		$this->container = new Container();
		$this->eventHandler = $this->container->build('\\Pixie\\EventHandler');

		$this->createAlias('QueryBuilder');
	}
}`

There might be more to it, and more options could be added, but this is a rough draft of how you could accomplish such thing.

**Comment by usmanhalalit** [comment]
Thanks @sirhubber

**Comment by acburdine** [comment]
I think there's a way to do this automatically through PDO's [getAttribute method](http://php.net/manual/en/pdo.getattribute.php). That would make the constructor above look something like:

```php
<?php

class ExtendedConnection extends PixieConnection {
    public function __construct(\PDO $connection) {
        $this->adapter = $connection->getAttribute(\PDO::ATTR_DRIVER_NAME);
        $this->setPdoInstance($connection);
        
        // ... same as above
    }
}

Might need to be some extra validation of the driver name though to ensure the adapter's right
