### ISSUE TITLE
Insert without data

### ISSUE THREAD

**Issue by AndreasFurster** [usmanhalalit/pixie#118]
Hello,

I'm trying to insert a row without any data. The ID is used to link some other tables to each other. 

All this function calls return an error:
`QB::table('tbl_name')->insert();`
`QB::table('tbl_name')->insert(null);`
`QB::table('tbl_name')->insert(array());`

How can i do this?

**Comment by sirhubber** [comment]
Yeah it seems there's an odd restriction for precisely this, I don't know why this was added.

https://github.com/usmanhalalit/pixie/blob/7df25f46bca44722a2d46a73cb07675751978a91/src/Pixie/QueryBuilder/Adapters/BaseAdapter.php#L135

Not that it's very common to insert empty rows, but what is possible in SQL should be possible through a QueryBuilder, one might think ;)

**Comment by AndreasFurster** [comment]
Yeah, i know it is strange! But there are some actions with triggers.

**Comment by usmanhalalit** [comment]
Removed the restriction. Didn't think of it :)
