### ISSUE TITLE
inject data in before-insert event

### ISSUE THREAD

**Issue by Kaimite** [usmanhalalit/pixie#119]
Hello, is it possible to do something like this : 

```php 
DB::registerEvent('before-insert', "members", function($queryBuilder)
{
	$insertData = $queryBuilder->addDataInSQL("mem_need_admin_confirm", 1);
}
);
```

I know how I can do it in after-insert event but is it possible to do it in before-insert event ?

Thank's

Kaimite

**Comment by usmanhalalit** [comment]
You can do things in before-insert, but what do you want to do here with `addDataInSQL`?

**Comment by Kaimite** [comment]
Hello, i want to add some data in the insert query. 

I get data from POST, for exemple a member subscription form : 

```php
$insertId = QB::table('members')->insert($_POST);

QB::registerEvent('before-insert', "members", function($queryBuilder)
{
    // I want to add mem_need_admin_confirm = 1
	
	// Don't kwno how to do to have this query : 
	// INSERT INTO members SET `mem_name` = 'Martin', `mem_login` = 'm.martin', ...., **`mem_need_admin_confirm` = 1;**
}
);
```

Thank's for your help :)

**Comment by usmanhalalit** [comment]
It's not possible :(

**Comment by eL-Prova** [comment]
@Kaimite it is possible in my fork. Take look at the pull request or my fork

**Comment by Kaimite** [comment]
Thank's. I will take a look.

Kaimite
