### ISSUE TITLE
Problems using Time Intervall

### ISSUE THREAD

**Issue by mewcrazy** [usmanhalalit/pixie#121]
Hello,

I'm trying to use a time based where clause with your QB:raw() function. But I just can't get it to work. Basically I wanna show all rows created in the last 24hours.

The where clause looks like this: (this works so far as a regular query)
```
WHERE tablename.created > DATE_SUB(NOW(), INTERVAL 24 HOUR)
```

Now I'm trying to achieve the same thing with the pixie sql markup:
```
$query->where('created', '>', QB::raw('DATE_SUB(NOW(), INTERVAL 24 HOUR'))->orderBy('created', 'DESC');
```

The query still runs fine, but the above where clause just gets ignored and sql server still outputs all rows. Could you help me figure out the right way to use it?

**Comment by usmanhalalit** [comment]
I'm not sure what result you're expecting. But I can see you're missing one parenthesis after 24 HOUR.
Overall do this
    $query = $qb->table('caliber')->where('created', '>', QB::raw('DATE_SUB(NOW(), INTERVAL 24 HOUR)'))->orderBy('created', 'DESC');

    var_dump($query->getQuery('select')->getSql());

Copy the query and run directly in you database client, then see if you're getting expected result.

**Comment by mewcrazy** [comment]
I did, but the outputted query looks like this: 

```
SELECT * FROM `cam_models` INNER JOIN `cam_models_meta` ON `cam_models_meta`.`model_id` = `cam_models`.`id` WHERE `created` > **?** ORDER BY `created` DESC
```

Basically I want to display only the newest  entries/rows of the last 24 hours since my table has 350.000 rows so far and it might rise up to a million by the end of this year.

I tried every code snippet I could find but I can't get any of them to work with QB::raw :/ Also I couldn't get this one to work:

```
$query = QB::query('select * from users_meta JOIN users ON users_meta.user_id=users.id where day(birthday) = day(DATE(NOW())) and month(birthday) = month(DATE(NOW())) ORDER BY name DESC LIMIT '.$entries_per_page);
```

I would appreciate so much if you could help me get those advanced queries to work in Pixie.
