### ISSUE TITLE
IDE Autocomplete

### ISSUE THREAD

**Issue by aiphee** [usmanhalalit/pixie#123]
Hi.

I'm used on PHPStorm autocomplete and PHPDoc in Pixie is not always right.

For example:
https://github.com/usmanhalalit/pixie/blob/master/src/Pixie/QueryBuilder/QueryBuilderHandler.php#L443
Should be
```PHP
    /**
     * @param $tables string Single table or multiple tables as an array or as
     *                multiple parameters
     *
     * @return QueryBuilderHandler
     */
```

Without this change, autocomplete doesnt work and IDE calls parameter Error. 
I'm using instance of Pixie like this:
```PHP
$connection = new Connection('mysql', $config);
$this->db   = new QueryBuilderHandler($connection);
```
I'm sure there is more of it, does that bother anyone else?

**Comment by skipperbent** [comment]
There must be something wrong with your PHPStorm setup or you might be using an old version.

It's absolutely normal to use ```@return static``` as return type. This ensures that the correct type is returned, if the class is extended by another class. You can use `self` as a return type aswell BUT this will only return the class-name of the current class, so it would give the wrong return type if the class was extended by another class.

`static::myMethod()` -> will return the from the parent class if extended
`self::myMethod()` -> will return the method in the current scope - much like using the classname itself, but smart if you don't want to rename everything if you decide to rename your class.

Hope it make sense :)

**Comment by aiphee** [comment]
I dont think there is something wrong with my PHPstorm.
Im using EAP version. 
The static is working when i use Pixie like this:
`QB::table('my_table')->find(3);`
But not when i use it like object 
`$iframe->db->table('messages')->get();`

So when i return `QueryBuilderHandler` it works for both, but when i return static, it works only for Static style.

Also, param line is wrong.
`@param $tables Single ...` should be `@param $tables string Single ...` (it's missing datatype)

**Comment by skipperbent** [comment]
You could add an annotation for your local property
```
@var \Pixie\QueryBuilder\QueryBuilderHandler
protected $db;
```

If you are using the alias ``QB`` you have to set the annotation yourself as it's created dynamically.

However it does work with my PhpStorm 2016.1 without any modifications:

![image1](http://i.imgur.com/Ivzmyat.png)
![image2](http://i.imgur.com/dOCwnxh.png)

*Param syntax is like this:*

`@param string Method Description` 

See more here:
https://www.jetbrains.com/help/phpstorm/2016.1/viewing-method-parameter-information.html?origin=old_help


But you're right about the datatype is missing. I can fix this no problem 👍  :D

**Comment by aiphee** [comment]
OK, thank you :+1:  :)

**Comment by cvng** [comment]
Hi,

For this specific issue, I ended up making a singleton and the IDE stop complaining:

```php
class DB extends \Pixie\QueryBuilder\QueryBuilderHandler
{
    private static $_instance = null;

    public function __construct()
    {
        $connection = new \Pixie\Connection('mysql', $config);
        parent::__construct($connection);
    }

    public static function getInstance()
    {
        if (is_null(self::$_instance))
            self::$_instance = new DB();

        return self::$_instance;
    }
}
```

Used like this:

```php
DB::getInstance()
```

Hope it will help others :)

**Comment by FinesseRus** [comment]
@skipperbent 

> But you're right about the datatype is missing. I can fix this no problem 👍 :D

Where did you fix it? I see it neither on the `master` branch nor on the `2.0`.
