### ISSUE TITLE
Backport changes to the 1.x branch

### ISSUE THREAD

**Issue by acburdine** [usmanhalalit/pixie#126]
Hey, thanks for the 2.0 update!

Would you be able to backport those changes to the 1.x branch? It's over a year old.

My request is because I'm on a server that can't reasonable upgrade to php 5.4 at the moment, and thus I can't use the 2.0 version. I was using `dev-master` in composer up until the recent release.

As far as I can tell, there aren't any bits of code that _don't_ work with php 5.3, so would it be possible to backport those (excepting the composer requirement of php >= 5.4)?

Thanks!

**Comment by eL-Prova** [comment]
Is it not easier to make a fork and make the changes by yourself? I think its over the top to request changes the backport where the version for php is less supported (most cases hosters etc will upgrade to newer versions..)

**Comment by acburdine** [comment]
Closing because implemented it myself (github.com/acburdine/pixie-backports)
