### ISSUE TITLE
Can't figure out how to add alias to tables

### ISSUE THREAD

**Issue by skipperbent** [usmanhalalit/pixie#133]
Cannot figure out how to create a join with the same table and renaming it using the `as` parameter to create an alias. Is it supported? If so, I would really like to see an example.

**Example:**

``` sql
SELECT event.* FROM event JOIN event AS parent ON parent.`id` = event.`parent_id` WHERE parent.`created_date` > NOW()
```

**Comment by eL-Prova** [comment]
Using a subquery can make it work.

**Comment by skipperbent** [comment]
No because subQueries makes aliases like this

```SQL
(SELECT * FROM Table WHERE 1=1) as MYALIAS
```

So if i need something like this the subQuery will not be enough

```sql
SELECT * FROM posts AS child WHERE (SELECT * FROM posts AS `parent` WHERE parent.`id` = child.`parent_id`)
```

**Comment by skipperbent** [comment]
It would make sense if there was an optional alias option on the `table` method.

**Comment by mrcnpdlk** [comment]
Solution below:

```
$query = $qb
    ->table(array('event' => 'eventOrAnotherAlias'))
    ->select('eventOrAnotherAlias.*')
    ->leftJoin(array('event', 'parent'), 'parent.id', '=', 'eventOrAnotherAlias.parent_id')
    ->where($qb->raw('parent.created_date > NOW()'))
```

I checked. It works!

**Comment by TCB13** [comment]
This can be closed. Probably related to #149. @usmanhalalit
