### ISSUE TITLE
cannot get two columns with same nam in multiple tables where joining

### ISSUE THREAD

**Issue by danielskowronski** [usmanhalalit/pixie#142]
I have relation in DB on two tables and I want to select two columns with same names on that tables. When I do so by `select(array("table1.id","table2.id"))` in return I get only one "id" field - value from table2 (probably value is overridden). 

Dirty solution is to use `\QB::raw("table1.id as tab1_id, table2.id as tab2_id")`. Is it desired state or will you fix pixie to detect such collisions and use as key full column name (with table name + dot).

**Comment by eL-Prova** [comment]
offcourse its overridden. The select will return 2 times the same name (id in your case) this is convert to a stdClass (similar like array key/value pair) where key already exists.

**Comment by marc937** [comment]
You don't have to use raw, you can use `select(['table1.id' => 'alias_id1', 'table2.id' => 'alias_id2'])`

**Comment by TCB13** [comment]
As @eL-Prova this is normal and expected behavior due to how PHP works. @marc937 is a good workaround for this issue so it can be closed @usmanhalalit .
