### ISSUE TITLE
Support `select <column> AS <alias>` by using an associative array in select method call

### ISSUE THREAD

**Issue by acburdine** [usmanhalalit/pixie#148]
It would be cool to have an extension to the `select` behavior which would allow you to pass in an associative array of columns to select. The keys of the array would be used as the aliases for the array values.

Example:

``` php
<?php

$qb->table('sometable')->select(
  array(
     'aliasA' => 'columnA',
     'aliasB' => 'columnB'
  )
)->get();

// Would generate the query "SELECT columnA AS aliasA, columnB AS aliasB FROM sometable"
```

Based on my knowledge of the existing codebase this shouldn't be too hard, and would be willing to work on a PR if it's desired.

As an extension it might be nice to be able to create a table alias as well (using a similar process in the `table` method), but I'm not 100% sure what all that would require code-wise.

**Comment by marc937** [comment]
You can already do this if I remember well, but its ['column' => 'alias', ...]

**Comment by mikegioia** [comment]
I think this should be closed out. However, the notes on how to do this should probably also be in the readme.

**Comment by acburdine** [comment]
Agreed, I'll try and open a PR sometime soon to add the docs to the README.
