### ISSUE TITLE
Don't work leftJoin(['table'=>'alias'],...)

### ISSUE THREAD

**Issue by DaaGER** [usmanhalalit/pixie#149]
If I use 
....
`->leftJoin(['dr_herbs'=>'herb'], 'mnn.parent_herb_id','=','herb.recommend')`
...
in query I get
`LEFT JOIN \`` AS `` ON `mnn`.`parent_herb_id` = `herb`.`recommend``

but I want
`LEFT JOIN \`dr_herbs` AS `herb` ON `mnn`.`parent_herb_id` = `herb`.`recommend``

**Comment by mrcnpdlk** [comment]
I have to use sth like this below:

```
->leftJoin(['dr_herbs,'herb'], 'mnn.parent_herb_id','=','herb.recommend')
```

There is not the associative array but simple two-arguments array.

**Comment by TCB13** [comment]
I guess this can be closed @usmanhalalit
