### ISSUE TITLE
Nested where clauses result in weird behavior

### ISSUE THREAD

**Issue by acburdine** [usmanhalalit/pixie#157]
So I couldn't think up a better title for this issue, but will attempt to explain what I was experiencing (and what I think is the issue).

Basically, I have a query that has several nested WHERE clauses (aka `WHERE (A OR (B AND C) OR D)`), and to generate those WHERE clauses I am using a custom where function, like so:

```php
$topLevelQuery->where(function ($qb) {
    // some code here
    
    // Exhibit A
    $subQuery = $qb->table('asdf')->select('somefield')->where('a', 'b');

    // more code here
});
```

Now, here's the weird behavior: The where clause of the subquery (exhibit A) is not applied to the $subQuery object. I would think that $qb->table() would return a completely brand-new instance of the QueryBuilderHandler, but it doesn't (more on that further down).

I also understand that most people use this library with the alias shortcut (aka `QB::table()`). While I realize that doing so would remedy this weird behavior, this is still an issue that likely needs to be addressed as it reflects somewhat bad practice.

I'm fairly certain the issue is caused because of [this line](https://github.com/usmanhalalit/pixie/blob/master/src/Pixie/QueryBuilder/QueryBuilderHandler.php#L456). The line is using `static` rather than `self`, and because of that the particular subclass of QueryBuilderHandler that happens to be inside the custom WHERE function is actually being returned rather than a completely new QueryBuilderHandler.

**Comment by usmanhalalit** [comment]
Nested and subqueries seem to have some issues, will mark those as "experimental".
