### ISSUE TITLE
Query Results as Standard Class Object

### ISSUE THREAD

**Issue by himanshuahuja96** [usmanhalalit/pixie#158]
```
$query1 = QB::query('select * from temp_requests where t_date BETWEEN CURRENT_DATE AND CURRENT_DATE+INTERVAL 7 day ORDER BY t_date ASC');
				print_r($query1->get());
```

Results Below
```
Array
(
    [0] => stdClass Object
        (
            [t_id] => 7
            [t_clubname] => test clubname
            [t_username] => test clubname
            [t_venue] => abc
            [t_date] => 2017-01-29
            [t_description] => Testttt desc
            [t_application] => 1485601307_Screenshot (39).png
            [t_stime] => 17:00:00
            [t_etime] => 18:05:00
            [t_timestamp] => 2017-01-28 16:31:47
            [trigger_event] => 
            [modified] => 2017-01-28 11:01:47
            [created] => 2017-01-28 11:01:47
        )

    [1] => stdClass Object
        (
            [t_id] => 6
            [t_clubname] => knock
            [t_username] => knock
            [t_venue] => plaza
            [t_date] => 2017-02-01
            [t_description] => hello
            [t_application] => dddeee
            [t_stime] => 15:00:00
            [t_etime] => 16:00:00
            [t_timestamp] => 2017-01-28 00:09:03
            [trigger_event] => 
            [modified] => 
            [created] => 
        )

)
```

But Find Only Returns Single Standard Class Object`
`````````
print_r($a=QB::table('members')->find(1, 'memberID'));`

`````````
```

stdClass Object
(
    [memberID] => 1
    [username] => admin
    [clubname] => Administrator
    [password] => hdhjhfjdhfdjhfjdh
    [role] => admin
    [email] => himanshuahuja93@gmail.com
    [active] => Yes
    [dis_en] => en
    [resetToken] => de34ebf2d2c257e96a2ab7bb05bb8624
    [resetComplete] => No
    [modified] => 
)

```
But We always need a array in result ,each time we need to convert it to array then we can use it.
Is there is way to get result like below

```
Array
(
    [password] => hdhjhfjdhfdjhfjdh
    [0] => hdhjhfjdhfdjhfjdh
    [username] => admin
    [1] => admin
    [clubname] => Administrator
    [2] => Administrator
    [role] => admin
    [3] => admin
    [memberID] => 1
    [4] => 1
)
```

**Please Suggest Any Way to Achieve this Directly**

**Comment by eL-Prova** [comment]
@himanshuahuja96 I have no idea how your database structure is designed. But If an user/member id is set in the first array, you can use the join function...So join on, examples are well written in the documentation. Otherwise I dont understand your question.

**Comment by himanshuahuja96** [comment]
I am asking that each find query results in **stdclass Object** and if get is used it returns **Array of Array** as result. IF i want a single result in array then firstly i have to convert it to array and then it becomes array of array i have shown above. I am asking that is there is default way to get a single array containing results..

**Comment by eL-Prova** [comment]
Your English makes it hard to read for me. If you select the rows, you join the other table. Your result will be extended. So each row has the columns and you can select the first. Thats enough am I correct? Otherwise can you make your example easier so the structure become more clear?

**Comment by TCB13** [comment]
@himanshuahuja96 from what I could understand here, you should be able to call: `->setFetchMode(\PDO::FETCH_ASSOC);` to force the output as an associate array or `->setFetchMode(\PDO::FETCH_OBJ);` to set it as `stdClass` objects.

Plase note that in raw queries seems like you always have to set otherwise you get weird results like you reported. I've come across this in the past.
