### ISSUE TITLE
Update docblock to include data types and better support IDEs

### ISSUE THREAD

**Issue by TCB13** [usmanhalalit/pixie#167]
Hello,

I've noticed that the docblock isn't very compatible with Phpstrom and 4k IDEs because it doesn't declare the datatype of the parameters.

Here is the declaration of `table()`:
![captura de ecra 2017-06-29 as 10 49 02](https://user-images.githubusercontent.com/6315832/27682501-b10ad028-5cba-11e7-80b2-64d2c2dfc6f8.png)

Since it lacks the datatype, Phpstorm complains right there... and then at my code:

![captura de ecra 2017-06-29 as 10 49 14](https://user-images.githubusercontent.com/6315832/27682516-c2c9b126-5cba-11e7-966a-013965123a57.png)

It is reading the "Single" as the datatype because there should be there an extra field specifying the datatype.

Have a nice day.

**Comment by FinesseRus** [comment]
This comments are called **PHPDoc**. I join the issue.

**Comment by TCB13** [comment]
@FinesseRus check #150 .

**Comment by TCB13** [comment]
Discussion continues on #150 .
