### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by mrjgreen** [usmanhalalit/pixie#17]
Laravel has support for transactions via the 

~~~
DB::transaction(function(){
     DB::insert(...);
     DB::delete(...);
     etc.....
});
~~~
which auto begins and commits a transaction before and after calling the callback function.

Would you consider adding a method to support this?

**Comment by acburdine** [comment]
@usmanhalalit has anyone worked on this at all? If not I can give it a shot.

**Comment by usmanhalalit** [comment]
@acburdine No one is working on it. It'd great if you can work on it.

**Comment by aiphee** [comment]
How to determine if the transaction was successful? Do i have to check every statement in it?

**Comment by acburdine** [comment]
@aiphee when I built transactions initially, I had it return true or false, and I changed that to return $this instead. Looking back that doesn't make much sense. I'll PR a fix to it
