### ISSUE TITLE
Add query tags similar to drupal

### ISSUE THREAD

**Issue by richwandell** [usmanhalalit/pixie#170]
I like Pixie so far. Considering using this for a piecemeal framework built from composer packages and micro frameworks.

I am happy to see that pixie has query events implemented that are related to tables, however there is a feature I would love to see which is "query tags" and the ability to alter queries using query events based on tag instead of table.

Is this already possible using pixie? 

Here is the relevant drupal article for example of the idea.
https://www.drupal.org/docs/7/api/database-api/dynamic-queries/query-alteration-tagging

**Comment by usmanhalalit** [comment]
@richwandell not possible now
