### ISSUE TITLE
How to use it properly for beginners. (?)

### ISSUE THREAD

**Issue by lordmemed** [usmanhalalit/pixie#171]
Hai. @lordmemed is here.

i just want to get a simple and clear examples for using it on abstract class and a class that extends from it.
sorry for requesting this from you @usmanhalalit or other people that might help. because i just a newcomer on PHP Classes.

here is my plan to do,
```
abstract class DatabaseQuery {} //that store all of queries using pixie, and then,
class DataClass extends DatabaseQuery {} //that store all function that another class use it to get data
```
i was try this by myself but return nothing.

so, could someone help me in this case?

**Comment by eL-Prova** [comment]
Hi,

Just copy the source.
Then Create your DatabaseQuery class
Creates the connection and stores in your DatabaseQuery in a field
Set a Facade for your request of the query builder.
Then create a query class or how you would like to call.
And just create a method with the query in it.

So in pseudo

```
class DatabaseQuery {
    public function _construct()
    {
         //Create a PDO instance and put in the instance of the field

        //Create your alias like 
        class_alias('AliasFacade', "YourAlias");
        AliasFacade::setQueryBuilderInstance(new QueryBuilderHandler($this));
    }
}

class DataQueryClass
{
   public function GetUserById($id)
   {
       return YourAlias::table("table_name_users")->find((int)$id, "id");
   }
}
```

**Comment by lordmemed** [comment]
thanks.
is that working with namespace?

**Comment by lordmemed** [comment]
hai, @eL-Prova. 
thanks for your answer.

how about abstraction and extends from it?
is there another example/pseudo-example maybe?

**Comment by eL-Prova** [comment]
Why you need an abstraction? The QueryBuilderHandler should be on his own. SOLID ;-) (Single responsibility)
I think you need to try it with this and when needed create new ticket so your question will be more focused on your problem.

**Comment by lordmemed** [comment]
try this, and get error ;
```
public function __construct()
    {
         //Create a PDO instance and put in the instance of the field
    	new Connection('mysql', $dbconf, 'QB');

        //Create your alias like 
        class_alias('AliasFacade', "MyAlias");
        AliasFacade::setQueryBuilderInstance(new QueryBuilderHandler($this));
    }
```
`Fatal error: Call to a member function getContainer() on null in vendor\Pecee\Pixie\QueryBuilder\QueryBuilderHandler.php on line 66`

any ideas? T_T

**Comment by eL-Prova** [comment]
1. Where is $dbconf coming from? Constructor? Then you miss argument
2. If you watch the source you see that $this->container is from the constructor which is Connection, that is $this not because it is DatabaseQuery. So new Connection should be put instead of the $this

**Comment by lordmemed** [comment]
@eL-Prova $dbconf is config array for pixie connection. 

oh,  i has solved that problem. thanks. 

just more question. 
1. is it okay use join for many tables and select all row then fetch from it? will it slow it down? or using too much cpu resources? 
2. is pixie automatically shutdown a connection after we use it? 

thank you very much. 

sincerely,  @lordmemed 

_Sent from my Polymer 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by usmanhalalit** [comment]
@lordmemed this is not a place for homework discussion. Please continue elsewhere.
