### ISSUE TITLE
Query cachin / MYSQLND_QC_ENABLE_SWITCH

### ISSUE THREAD

**Issue by mewcrazy** [usmanhalalit/pixie#179]
Hey,

Is it possible to achieve query caching with pixie sql yet? I have a statistics page with a ->count() query, usually no problem, but in this case my table has 5 million rows and the count takes up to 5seconds. So I need some way to easily cache it. I read about MySQL caching and would like to use it with pixie:

http://php.net/manual/de/mysqlnd-qc.quickstart.caching.php

Kind Regards,
Dennis

**Comment by TCB13** [comment]
@mewcrazy have you considered other caching methods built in on MySQL?

**Comment by usmanhalalit** [comment]
@mewcrazy not really interested in making caching a part of the library, it can be done outside of Pixie though. Thanks for your thoughts though.
