### ISSUE TITLE
optimize query with use index

### ISSUE THREAD

**Issue by StephanKrauss** [usmanhalalit/pixie#181]
Hello,

i have a query.
Do pixie support the using from index.

http://code.openark.org/blog/mysql/7-ways-to-convince-mysql-to-use-the-right-index

Your sincerly

Stephan

**Comment by eL-Prova** [comment]
Hi, it does not have that support yet. However you can make a PR for the support.

**Comment by usmanhalalit** [comment]
@StephanKrauss Not supported. And would not like to add support either as it's too specific.
