### ISSUE TITLE
Specifying FetchMode with options

### ISSUE THREAD

**Issue by vikkio88** [usmanhalalit/pixie#185]
I tried to specify to fetch mode globally with 'options'
```php
'options' => [
PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
]
```

but basically that does not matter because it is set anyway on `->get()` via 
```
$result = call_user_func_array(array($this->pdoStatement, 'fetchAll'), $this->fetchParameters);
```
on https://github.com/usmanhalalit/pixie/blob/master/src/Pixie/QueryBuilder/QueryBuilderHandler.php#L178

And if you try to set it on the `QueryBuilderHandler` using the `setFetchMode()` method, you will lose it next time you are going to use a `->table()`, as it is creating a new instance of QB.

**Comment by TCB13** [comment]
You're correct and we have been over this in the past. #143. They only place where `FETCH_MODE` is kept is on raw queries #68. This would be a nice improvement but @usmanhalalit probably need to check it.

**Comment by vikkio88** [comment]
I opened a PR with a possible fix https://github.com/usmanhalalit/pixie/pull/183
