### ISSUE TITLE
Usage in a namespaced application and running CREATE statements

### ISSUE THREAD

**Issue by randohinn** [usmanhalalit/pixie#194]
Hi!

1. What's the best way to use this in a namespaced application, so that all my classes under namespace `whatver` have access to the connection QB? 

2. What's the best way to use this for running table creation statements?

**Comment by usmanhalalit** [comment]
1. `QB` is meant for this, it's like global you'll have access to `\QB` anywhere in your app.

2. Table creation is not supported but feel free to use `QB::query('CREATE TABLE....')`

**Comment by randohinn** [comment]
Ah, thanks. Early in the morning, and forgot the `\`
