### ISSUE TITLE
How can i use external variable in transactions?

### ISSUE THREAD

**Issue by JKwang00** [usmanhalalit/pixie#205]
hello everyone.
I need your help and i hope to get solution of it.
I tried below code.
$userid = "test";
\QB::transaction(function ($qb) {
    echo $userid;
    $qb->table("user_table")->where("userid","=",$userid)->update(array('user_status'=>'1'));
});

i can't get $userid
let me kinda know how can i get external variable.

best regards.

**Comment by eL-Prova** [comment]
You need to assign `global` 

So code need to be:

```
$userid = "test";
\QB::transaction(function ($qb) {
global $userid;
echo $userid;
$qb->table("user_table")->where("userid","=",$userid)->update(array('user_status'=>'1'));
});
```

**Comment by JKwang00** [comment]
Thank you for reply.
