### ISSUE TITLE
join on subquery support

### ISSUE THREAD

**Issue by 82rules** [usmanhalalit/pixie#52]
If this is something pixie currently support I'd like to know
Otherwise i'd like to expand support to join on subqueries 
for example

select * from table1 alias1
    inner join (select id from table2 where field = 1) alias2 on alias2.id =alias1.id

i see the join param expects a string rather than an object so right now my ideal setup is not funcitonal: 

$subquery = QB::table('table2')->select('name')->select('id)->where('field','=',1); 
$query = QB::table('table1)->innerJoin(QB::table(QB::subQuery($subquery,'alias2')),'alias1.id','=','alias2.id'); 

I know the sql is a simple and dumb example I'm in a real world situation where we join on a subquery and I'd like to accomplish this without using raw

**Comment by usmanhalalit** [comment]
Unfortunately, Pixie doesn't support it.

**Comment by 82rules** [comment]
I was able to use the $query->getQuery()->getRawSql() method to make a raw subselect, it was an acceptable comprimise as I can still build my subquery with pixie

**Comment by usmanhalalit** [comment]
Yep, glad to hear that!
