### ISSUE TITLE
PDO::ATTR_ERRMODE

### ISSUE THREAD

**Issue by TCB13** [usmanhalalit/pixie#59]
Hello,

I just noticed that by default `QueryBuilderHandler` always sets this:

```
$this->pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
```

Why is this behavior forced? I tried to change the error mode like:

```
$mysql = new \Pixie\QueryBuilder\QueryBuilderHandler($mysqlConnection);
$pdo = $mysql->pdo();
$pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_WARNING);
```

But it always trow exceptions. By some reason is ignoring my attribute change...

Thank you.

**Comment by neoascetic** [comment]
Yeah, it is better to be able to override this attribute with connection options. That line definitely should go to connection adapter class.

**Comment by TCB13** [comment]
As you can see I was unable to set it at PDO level.

On a usual PDO only project I would do something like:

		$dbUrl = "mysql:host=" . $server . ";port=" . $port . ";dbname=" . $db . ";charset=utf8mb4";

		try {
		   parent::__construct($dbUrl, $user, $passwd);
		} catch (\PDOException $e) {
		   print "Error establishing a database connection.";
		   exit();
		}
		
		$this->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_SILENT);

However as you saw on the code I posted, that takes a similar approach to this, but includes pixie, doesn't work.

I don't know is this attribute change can be implemented on the connection options array. From my understanding (probably not correct) the `\PDO::ATTR_ERRMODE` only works after the connection is open.

**Comment by usmanhalalit** [comment]
Thanks @TCB13, keeping it open. As @neoascetic suggested allow overriding can be a good way to go.

**Comment by vincentwinkel** [comment]
Hi,
Thanks for this amazing query builder.
What about this issue ?
