### ISSUE TITLE
->setFetchMode(\PDO::FETCH_ASSOC) on all queries

### ISSUE THREAD

**Issue by TCB13** [usmanhalalit/pixie#63]
Hello,

I can't find a way to use the `->setFetchMode(\PDO::FETCH_ASSOC)` method with raw queries...

Is this possible? What about other queries?

Thank you.

**Comment by neoascetic** [comment]
This should work. How you build your query exactly, may you provide an example?

**Comment by TCB13** [comment]
Before speaking about raw queries, what's the correct way to return an array on this case?
```````
$query = QB::table('my_table')->where('name', '=', 'Sana');
$result = $query->get();
```````

This will return an object. Is there a way I can make the `get()` return an array instead? Let's say that returning an object and then casting it to an array is just inefficient since this can be done at the PDO level from the beginning.

I think `->get()` should accept a parameter defining the fetch type to be passed to PDO, like:

`->get(\PDO::FETCH_ASSOC)`

Or... we should be able to do something like:

```````
$query = QB::table('my_table')
->where('name', '=', 'Sana')
->setFetchMode(\PDO::FETCH_ASSOC)
$result = $query->get();
```````

What's your opinion?

Thank you.

**Comment by neoascetic** [comment]
`setFetchMode(PDO::FETCH_ASSOC)` **is** the correct way to fetch entities as array.

**Comment by TCB13** [comment]
I'm kinda confused, check this example:
``````
<?php 
require_once "vendor/autoload.php";

$config = [
	"driver"    => "mysql",
	"host"      => "127.0.0.1",
	"port"      => 3306,
	"database"  => "test",
	"username"  => "root", 
	"password"  => "root",
	"charset"   => "utf8mb4",
	"collation" => "utf8mb4_unicode_ci",
	"prefix"    => "", 
	"options"   => [
		\PDO::MYSQL_ATTR_INIT_COMMAND 	=> "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'"
	],
];

// Start DB Connection
try {
	$mysqlConnection = new \Pixie\Connection('mysql', $config, 'DB');
} catch (\PDOException $e) {
	print "Error establishing a database connection.";
	exit();
}

// Instantiate a shared QueryBuilder
$db = new \Pixie\QueryBuilder\QueryBuilderHandler($mysqlConnection);

// Query Example
$query = $db->table("page")
			->where("title", "=", "test title")
			->setFetchMode(\PDO::FETCH_ASSOC);

$result = $query->get();

var_dump($result);
``````

This returns:

`Fatal error: Call to undefined method Pixie\QueryBuilder\QueryBuilderHandler::setFetchMode() in index.php on line 34`

Isn't this implemented yet, the way you said, or I'm getting it wrong.

Thank you.

**Comment by neoascetic** [comment]
Do you have up-to-date version of Pixie?

**Comment by TCB13** [comment]
I was getting it using `"usmanhalalit/pixie": "1.*@dev"` on `composer.json`... I changed it to `dev-master` and not it works. Sorry and thank you for the feedback ;)

**Comment by neoascetic** [comment]
@TCB13 You are welcome. I guess issue now may be closed then.

**Comment by TCB13** [comment]
Sure ;)

**Comment by TCB13** [comment]
Note, I'll fork the documentation to add this. ;)

**Comment by kikideveloper** [comment]
<select class="form-control">
					<?php
						echo "<option value='0'>-</option>";
						$data = $base->select("level");
						// $q=;
						// foreach ($q as $key => $value) {
						// }
						try {
							while ($row=$data->fetch(PDO::FETCH_ASSOC)) {
								echo "<option value='$row[id]'>$row[name]</option>";
							}
						} catch (PDOException $e) {
							die($e->getMessage());
						}
					?>
				[`</select>```](

> 
![screenshot_2](https://user-images.githubusercontent.com/25499270/35547618-99fa36e4-05ac-11e8-9423-be536ea6ed3b.png)
if like this what is the problem?
I'm sorry, because I'm a beginner

**Comment by usmanhalalit** [comment]
@kikideveloper Please check the docs and do it that way.

**Comment by kikideveloper** [comment]
which documents @usman.it
