### ISSUE TITLE
->setFetchMode() kept between raw queries

### ISSUE THREAD

**Issue by TCB13** [usmanhalalit/pixie#68]
Hello,

There seems to be a behaviour mismatch between the way raw queries and pixie queries handle `->setFetchMode()`.

For instance, If I do:
`````
$query = $db->table("page")
			->where("title", "=", "test title")
			->setFetchMode(\PDO::FETCH_ASSOC);
`````

The returned array will give me an array as expected. Next time if I just issue:

`````
$query = $db->table("page")
			->where("title", "=", "test title");
`````

Without specifying a fetch mode, it will default to `PDO::FETCH_OBJ` as expected. 

This is fine, however in raw queries, the fetch mode value is kept between two queries:
`````
$query = $db->query("select * from page where title = 'test title'");
$query->setFetchMode(\PDO::FETCH_ASSOC);
`````
Will return an array as expected. If I issue next, a query without specifying a fetch mode:

`````
$query = $db->query("select * from page where title = 'test title'");
`````

It will return an array as well. It will keep returning arrays until I manually set it to return objects again. 

Why isn't the fetch mode changed to the default `PDO::FETCH_OBJ` after `$query->get()` similarly to what happens in non-raw queries?

Thank you.

**Comment by neoascetic** [comment]
You are reusing same query builder object in each query, so there is nothing strange.

**Comment by TCB13** [comment]
So, why do non-raw queries always "reset" the fetch mode?

**Comment by neoascetic** [comment]
What if you don't want it to be resetted? There is `newQuery` method also.

**Comment by usmanhalalit** [comment]
@TCB13 in normal queries we create a new instance of query builder each time `table()` is called. We do this so that we can run multiple queries in parallel. But for raw queries, usually, there is no such need. But I don't think it would be bad to have same behavior for both. So keeping your issue open.

**Comment by TCB13** [comment]
@usmanhalalit I agree with the behavior. This way we don't really need to instante a query builder every time we wan't to do a query, however I guess this difference should be documented. Until a few days ago I was expecting raw queries to follow the same policy.
