### ISSUE TITLE
where string

### ISSUE THREAD

**Issue by Kaimite** [usmanhalalit/pixie#69]
Hello, 

is it possible to specify a "where" like this : 

```QB::table('my_table')->where("`field` > 35 OR `field2` != 'test' ");```

I want to specify a where string in a form field. 

Thank's for your answers and sorry for my english :)

Kaimite

**Comment by neoascetic** [comment]
Hi. [Raw expressions] (https://github.com/usmanhalalit/pixie#raw-expressions) should work: `->where(QB::raw("your string"))`.

**Comment by Kaimite** [comment]
It's perfect :) 

Thank's

**Comment by Kaimite** [comment]
Hello, 

Sorry, i come back a little late but it does not work :(

Here i my code : 
```
$query      = DB::table($this -> _tableName);
$query -> where( DB::raw($this -> _params['where']) );
$query -> orderBy($this -> _params['order'][0], $this -> _params['order'][1]);
$query -> limit( $this -> _params['limit'] );
```

And the result : 
SELECT * FROM articles WHERE rub_id = 5  **NULL** ORDER BY art_date_crea DESC LIMIT 50

I don't know how to remove the **NULL** in my query string. Any idea ? 

Thank's for your help.

Kaimite

**Comment by neoascetic** [comment]
This should work, [as per tests](https://github.com/usmanhalalit/pixie/blob/master/tests/Pixie/QueryBuilderBehaviorTest.php#L74). Are you using the latest pixie?

**Comment by Kaimite** [comment]
Can't do update with composer... Maybe bug from my computer. 
Done with git and it works :D 

Thank's a lot !
