### ISSUE TITLE
Insert Raw() at any given point

### ISSUE THREAD

**Issue by TCB13** [usmanhalalit/pixie#72]
Hello,

I was noticing this isn't possible, for e.g.:

``````
$query = QB::table("example");
$query->select("id", "name");
$query->raw("where id != null");
$result = $query->get();
``````

The line `$query->raw("where id != null");` seems to be ignored. 

Is there any specific reason why I can't insert a `raw()` on the middle of the query? I guess it wasn't implement do the fluid interface, because we never know what parts of the query are set first...

**Comment by neoascetic** [comment]
Calling `$query->raw` gives you raw statement wrapper but does not inject it to the current query. This works as expected. You should use special methods to generate parts of SQL query (such as `select`, `where`, `orderBy`, etc). If you want to add some raw value in any particular point of any of these parts, you need to pass raw value as argument to these methods, like that: `$q->where($q->raw('foo'))->orderBy($q->raw('bar'))`.

**Comment by TCB13** [comment]
Why don't we have a `raw()` able to inject into the current query? Maybe with a different name...

**Comment by neoascetic** [comment]
Because builder builds resulting SQL query from chunks as per SQL specification. If you need something custom, you may use raw queries without builder.

**Comment by usmanhalalit** [comment]
I think it won't be possible.
