### ISSUE TITLE
after-insert event  query object in params ? 

### ISSUE THREAD

**Issue by Kaimite** [usmanhalalit/pixie#78]
Hello, 
is it possible to have the "query object" in after-insert event ?
I use after-insert / update / delete events to log each queries in a flat file. 
If my sql server crash I can restore all queries done after my daily backup. 

but in the after-select event I can't get query with : 
```php
$query = $queryObject -> getRawSql();
```

something like that : 
```php
QB::registerEvent('after-insert', ':any', function($queryBuilder, $insertId, $executionTime, $queryObject)
	{
		logQuery($queryObject -> getRawSql());
	}
);
```

I tried this : 
```php
$queryObj   = $queryBuilder -> getQuery();
$query = $queryObj -> getRawSql();
```
but it's not the good query :'(

Thank's !

**Comment by usmanhalalit** [comment]
Sorry, after insert doesn't receive the query object..

By the way, if your database server crashes, then after-insert won't be called anyway.

**Comment by Kaimite** [comment]
Hello, 

I backup my SQL data every night but il my server crash at 09 pm I loose everything between the backup time and 09 am. 

I log every update, delete, insert queries in a daily file. If my SQL server crash at 09 pm i cant restore my last backup + my log file to restore every differents queries beteween backup time and 09 pm :) 

This way I loose a minimum. 

I'll try to do it a different way... 

Thank's again for your work! 

Kaimite
