### ISSUE TITLE
Just the query.

### ISSUE THREAD

**Issue by IngwiePhoenix** [usmanhalalit/pixie#79]
I am using a migration framework called LibMigrate. It expects me to return the SQL it should run. That is why I do not want to open yet another connection if that is not even required. So...what is the correct way to just obtain the SQL without conencting?

Kind regards, Ingwie.

**Comment by usmanhalalit** [comment]
Ingwie, there in no way without some hacks. Btw, you can use the first connection, the query won't run if you get just SQL.
