### ISSUE TITLE
whereNot is not working for some reason

### ISSUE THREAD

**Issue by rukshn** [usmanhalalit/pixie#80]
When I try to run a query with whereNot I get the following error,

Fatal error: Call to undefined method Pixie\QueryBuilder\QueryBuilderHandler::whereNot() in /home/ubuntu/workspace.....

**Comment by usmanhalalit** [comment]
If you're using 1.x (the default) version then whereNot is not in it, it's on dev-master. Ot you can just use ->where('value', '!=', 'Your value')
