### ISSUE TITLE
Count not working?

### ISSUE THREAD

**Issue by iautomation** [usmanhalalit/pixie#83]
Using the .*@dev composer version on a server running MariaDB, I cannot seem to get count to work.

Thankyou

**Comment by usmanhalalit** [comment]
Can you please test with MySQL?

**Comment by iautomation** [comment]
I've now tried with mysql, with the same result, a return of 0.

The following code is:

```
$config = array(
	'driver'	=> 'mysql', // Db driver
	'host'		=> 'localhost',
	'database'	=> '****',
	'username'	=> '****',
	'password'	=> '****',
	'charset'	=> 'utf8', // Optional
	'collation' => 'utf8_unicode_ci', // Optional
	'prefix'	=> '', // Table prefix, optional
	'options'	=> array( // PDO constructor options, optional
		PDO::ATTR_TIMEOUT => 5,
		PDO::ATTR_EMULATE_PREPARES => false,
	),
);

new \Pixie\Connection('mysql', $config, 'db');
$count = db::table('ia')->count();
echo count;
```

The table consists of one row.

Best

**Comment by iautomation** [comment]
Sorry for the waste of time. The issue was that I had forced PDO::FETCH_NUM in Pixie/QueryBuilder/QueryBuilderHandler.php on line 50 in order to get array results; and the count function is hard coded for objects.

**Comment by usmanhalalit** [comment]
Should be fixed, thanks for reporting.

**Comment by bkielbasa** [comment]
I have the same problem. Here is my code:

    public function getRecruitedQuery()
    {
        return \QB::table('user')
            ->where('typ', UserType::W)
            ->where('edycja', _EDYCJA)
            ->where('status', WStatus::RECRUITED);
    }

and when I try to count the results 

    $recruitedCount = $wRepository->getRecruitedQuery()->count();

I receive error: 

    Fatal error: Cannot use object of type stdClass as array in /path/to/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php on line 258

I had to downgrade PIxie to commit 9555c417ba785184503396f0f0902401d9603190 to make it working back.

**Comment by marc937** [comment]
Pull request #87 should correct it.

**Comment by bkielbasa** [comment]
I can confirm that if fixes the issue
