### ISSUE TITLE
Raw query as value breaking all WHERE clauses

### ISSUE THREAD

**Issue by TCB13** [usmanhalalit/pixie#90]
Good morning,

I was trying the following:
```````
$query = $db->table($groupTbl)
			->select("id")
			->where($db->raw("`" . $groupTbl . "`.dateCreated"), ">", $db->raw("'2015-04-20 15:00:00'"));
```````

However it doesn't work properly as I get the following raw query:
```````
SELECT `id` FROM `Funcionarios\Dados` WHERE `Data`.dateCreated
```````

As you can see the second part of the query was omitted. It's missing `> '2015-04-20 15:00:00'`. This issue seems to affect all `where` queries like `whereBetween`, `orWhere` etc. Is there any specific reason for this inconsistency?

Thank you.

**Comment by marc937** [comment]
Use

```php
$query = $db->table($groupTbl)
            ->select("id")
            ->where($db->raw("`" . $groupTbl . "`.`dateCreated` > '2015-04-20 15:00:00'));
```

**Comment by TCB13** [comment]
@marc937 that's what I've been doing for a while... however I feel like it should accept multiple `raw()` calls. It makes more sense that way.
