### ISSUE TITLE
How Extends QueryBuilderHandler?

### ISSUE THREAD

**Issue by devsalman** [usmanhalalit/pixie#95]
Hello, im trying to integrating your querybuilder into my own framework and i need to extends your QueryBuilderHandler into my Model class so that i can do like this in my Controller:

```php
//inject User model
function __construct(User $user)
{
     $this->user = user;
}

function login(Request $request)
{
    $user = $this->user->find(1);
}
```

to achieve that im trying to extends your QueryBuilderHandler class like this:
```php
class Model extends QueryBuilderHandler
{
    protected $table = "";

    function __construct()
    {
        $config = [
            'driver'    => $_ENV['DB_DRIVER'],
            'host'      => $_ENV['DB_HOST'],
            'database'  => $_ENV['DB_NAME'],
            'username'  => $_ENV['DB_USERNAME'],
            'password'  => $_ENV['DB_PASSWORD'],
            'charset'   => $_ENV['DB_CHARSET'],
            'collation' => $_ENV['DB_COLLATION'],
            'prefix'    => $_ENV['DB_PREFIX'],
        ];

        if($this->table === "")
        {
            $classPath = explode('\\', get_called_class());
            $tableName = strtolower(end($classPath));
            $this->table = $tableName . 's';
        }

        $connection = new Connection($config['driver'], $config);
        parent::__construct($connection);
        $this->table($this->table);
    }
}

class User extends Model
{
    function __construct()
    {
        parent::__construct();
    }
}
```

But i always get this error:
>
Uncaught exception 'PDOException' with message 'SQLSTATE[08004] [1040] Too many connections' in D:\Repository\eshop\vendor\usmanhalalit\viocon\src\Viocon\Container.php:138 Stack trace: #0 [internal function]: PDO->__construct('mysql:host=loca...', 'devel', 'password123') #1 D:\Repository\eshop\vendor\usmanhalalit\viocon\src\Viocon\Container.php(138): ReflectionClass->newInstanceArgs(Array) #2 D:\Repository\eshop\vendor\usmanhalalit\viocon\src\Viocon\Container.php(110): Viocon\Container->instanciate('\\PDO', Array) #3 D:\Repository\eshop\vendor\usmanhalalit\pixie\src\Pixie\ConnectionAdapters\Mysql.php(25): Viocon\Container->build('\\PDO', Array) #4 D:\Repository\eshop\vendor\usmanhalalit\pixie\src\Pixie\Connection.php(93): Pixie\ConnectionAdapters\Mysql->connect(Array) #5 D:\Repository\eshop\vendor\usmanhalalit\pixie\src\Pixie\Connection.php(51): Pixie\Connection->connect() #6 D:\Repository\eshop\app\Models\Model.php(32): Pixie\Connection->__construct('mysql', Array) #7 D:\Repository\eshop\app\Models\User.php( in D:\Repository\eshop\vendor\usmanhalalit\viocon\src\Viocon\Container.php on line 138

is there something wrong with my aproach? im very appreciate if you can give me some advice :)

**Comment by devsalman** [comment]
i found the problem, the problem lies in this statement `$this->table($this->table);`, i tought that statement only set the table name and return the `QueryBuilderHandler` instance but this statement initialize the connection too.

```php
    /**
     * @param $tables
     *
     * @return static
     */
    public function table($tables)
    {
        $instance = new static($this->connection);
        $tables = $this->addTablePrefix($tables, false);
        $instance->addStatement('tables', $tables);
        return $instance;
    }
```
So, i change my approach like this:

```php
namespace App\Models;

use Pixie\Connection;
use Pixie\QueryBuilder\QueryBuilderHandler;

class Model extends QueryBuilderHandler
{
    protected $table = "";

    function __construct(Connection $connection)
    {
        if($this->table === "")
        {
            $this->setDefaultTableName();
        }

        parent::__construct($connection);
        $this->addStatement('tables', $this->table);
    }

    private function setDefaultTableName()
    {
        $classPath = explode('\\', get_called_class());
        $tableName = strtolower(end($classPath));
        $this->table = $tableName . 's';
    }
}
```

**Comment by usmanhalalit** [comment]
You should connect to db only once, maybe somewhere in your app's bootstrap file.
